#229 submit
lfapac-open-source-evangelist/translation pull request #242
Opened 2023-03-24 04:37 UTC by zys0070

2023-03-27 07:14 UTC, zRich requested changes
保持原文在上，译文在下。

2023-03-27 09:59 UTC, zys0070 commented
已修改

2023-03-31 02:47 UTC, zRich requested changes
原文和译文之间需要增加一个空行，否则显示的时候会合并在一起。

2023-03-31 02:47 UTC, zRich commented on manageing-os-projects-on-github/03.md
> + 对于托管在GitHub上的开源项目来说，清晰而详细的文档至关重要。它有助于确保其他开发人员易于理解和使用该项目，从而增加贡献者和用户的数量。良好的文档应包括项目目的概述、使用说明以及任何依赖关系或要求。它还应包括代码、工作原理和任何已知问题或限制的详细解释。清晰的文档可以让其他开发人员更容易理解项目并做出贡献。同时，它也可以更容易地维护项目，因为开发人员将更好地了解代码的工作原理并可以自信地进
![image](https://user-images.githubusercontent.com/2752413/229010050-c1e29f0f-e365-4699-b4f7-06dc4a453701.png)

原文和译文之间需要增加一个空行，否则显示的时候会合并在一起。

下面的内容也有这种情况。

2023-03-31 05:13 UTC, zys0070 commented on manageing-os-projects-on-github/03.md
> + 对于托管在GitHub上的开源项目来说，清晰而详细的文档至关重要。它有助于确保其他开发人员易于理解和使用该项目，从而增加贡献者和用户的数量。良好的文档应包括项目目的概述、使用说明以及任何依赖关系或要求。它还应包括代码、工作原理和任何已知问题或限制的详细解释。清晰的文档可以让其他开发人员更容易理解项目并做出贡献。同时，它也可以更容易地维护项目，因为开发人员将更好地了解代码的工作原理并可以自信地进
已修改

2023-04-06 06:55 UTC, zRich approved these changes

2023-04-06 06:55 UTC, merged