translation of  09.md bvoo
lfapac-open-source-evangelist/translation pull request #298
Opened 2023-05-07 13:52 UTC by voidxb

2023-05-08 03:34 UTC, node submitted a review, later dismissed

2023-05-08 03:34 UTC, node commented on The-business-value-of-OSPO/09.md
> +TODO是一个由来自不同部门和地区的OSPO从业者组成的全球社区。其全体成员包括来自90多个组织的代表，他们在成功运行开源程序方面具有丰富的经验。TODO旨在促进通过OSPO管理开源项目的最佳实践、工具和指导方面的合作。
开源程序 -> 开源专项 或 开源项目办公室

2023-05-08 03:34 UTC, node commented on The-business-value-of-OSPO/09.md
> +通过分享经验和开发通用工具，TODO寻求改善OSPO的培养和教育。搜索TODO正在进行的行动，如OSPOlogy和活跃的工作组，并查看OSPO全景图、OSPO 101培训模块和TODO指南以了解更多信息。
培养和教育  -> 应用和教育

2023-05-08 03:34 UTC, node commented on The-business-value-of-OSPO/09.md
> +通过分享经验和开发通用工具，TODO寻求改善OSPO的培养和教育。搜索TODO正在进行的行动，如OSPOlogy和活跃的工作组，并查看OSPO全景图、OSPO 101培训模块和TODO指南以了解更多信息。
搜索 -> 探索

2023-05-08 03:34 UTC, node commented on The-business-value-of-OSPO/09.md
> +成立于2021年的[Linux基金会研究院](http://Linux%20Foundation%20Research)探索了开源合作日益扩大的规模，深入了解了新兴的技术趋势、最佳实践以及开源项目的全球影响。通过利用项目数据库和网络，以及对定量和定性方法论最佳实践的承诺，Linux基金会研究院正在为世界各地的组织创建开源见解的首选存储库。
> 探索了开源合作日益扩大的规模
 
在探索开源协作规模的日趋增长，

2023-05-08 03:34 UTC, node commented on The-business-value-of-OSPO/09.md
> +成立于2021年的[Linux基金会研究院](http://Linux%20Foundation%20Research)探索了开源合作日益扩大的规模，深入了解了新兴的技术趋势、最佳实践以及开源项目的全球影响。通过利用项目数据库和网络，以及对定量和定性方法论最佳实践的承诺，Linux基金会研究院正在为世界各地的组织创建开源见解的首选存储库。
> 深入了解了新兴的技术趋势、最佳实践以及开源项目的全球影响。

以及提供对新兴技术趋势的洞察力、最佳实践及开源项目的全球影响。

2023-05-08 03:34 UTC, node commented on The-business-value-of-OSPO/09.md
> +本报告根据[知识共享-署名-无衍生 4.0 国际公共许可证](https://creativecommons.org/licenses/by-nd/4.0/)获得许可。
本报告使用 XXXX 许可。

2023-05-08 03:34 UTC, node commented on The-business-value-of-OSPO/09.md
> +要引用这项工作，请引用以下内容：Emily Omier、Chris Aniszczyk和Ana Jiménez Santamaría，“OSPO的商业价值：探索组织为什么创建、维持和扩展开源项目办公室（OSPO）”，Linux基金会，2023年3月Georg Kunz、Leslie Hawthorn和Kimberly Craven 所著的前言。
> 要引用这项工作，请引用以下内容：

请参考以下内容引用本报告：

2023-05-10 06:26 UTC, node requested changes

2023-05-10 06:26 UTC, node commented on The-business-value-of-OSPO/09.md
> +本报告根据[知识共享-署名-无衍生 4.0 国际公共许可证](https://creativecommons.org/licenses/by-nd/4.0/)获得许可。
CC BY 许可证名称可不翻译

2023-05-13 12:35 UTC, voidxb commented on The-business-value-of-OSPO/09.md
> +通过分享经验和开发通用工具，TODO寻求改善OSPO的培养和教育。搜索TODO正在进行的行动，如OSPOlogy和活跃的工作组，并查看OSPO全景图、OSPO 101培训模块和TODO指南以了解更多信息。
办公室用应用合适吗？我理解是在公司内复制培养出好的开源办公室

2023-05-13 12:36 UTC, voidxb commented on The-business-value-of-OSPO/09.md
> +通过分享经验和开发通用工具，TODO寻求改善OSPO的培养和教育。搜索TODO正在进行的行动，如OSPOlogy和活跃的工作组，并查看OSPO全景图、OSPO 101培训模块和TODO指南以了解更多信息。
我理解他的意思是就是去查询搜索这些活动和文档，了解更多内容，探索反而比较奇怪

2023-05-13 12:39 UTC, voidxb commented on The-business-value-of-OSPO/09.md
> +本报告根据[知识共享-署名-无衍生 4.0 国际公共许可证](https://creativecommons.org/licenses/by-nd/4.0/)获得许可。
这是规范吗，这个许可证的翻译国内是有名称对应的

2023-05-14 12:52 UTC, node commented on The-business-value-of-OSPO/09.md
> +通过分享经验和开发通用工具，TODO寻求改善OSPO的培养和教育。搜索TODO正在进行的行动，如OSPOlogy和活跃的工作组，并查看OSPO全景图、OSPO 101培训模块和TODO指南以了解更多信息。
OK

2023-05-14 12:52 UTC, node commented on The-business-value-of-OSPO/09.md
> +通过分享经验和开发通用工具，TODO寻求改善OSPO的培养和教育。搜索TODO正在进行的行动，如OSPOlogy和活跃的工作组，并查看OSPO全景图、OSPO 101培训模块和TODO指南以了解更多信息。
采用？培养和教育比原文的adoption相比损失了一些信息。 OSPO是一种典型实践，应用和采用感觉都适合。

2023-05-15 16:06 UTC, voidxb commented on The-business-value-of-OSPO/09.md
> +本报告根据[知识共享-署名-无衍生 4.0 国际公共许可证](https://creativecommons.org/licenses/by-nd/4.0/)获得许可。
ok

2023-05-16 00:32 UTC, node approved these changes
LGTM

2023-05-16 00:32 UTC, merged