Translate CNCF blog: CNCF Automates Kubernetes SecOps With Kyverno
lfapac-open-source-evangelist/translation pull request #423
Opened 2024-11-21 08:27 UTC by terizhao

solve this issue: https://github.com/lfapac-open-source-evangelist/translation/issues/422

2024-11-21 09:14 UTC, windsonsea commented
hmmm, seems nothing committed.

2024-11-22 03:55 UTC, zRich requested changes

2024-11-22 03:55 UTC, zRich commented on blog/CNCF Automate Kubernetes SecOps With Kyverno.md
> +本月在盐湖城举行的KubeCon + CloudNativeCon 北美大会上，开源Kubernetes策略引擎技术Kyverno，正式获得云原生计算基金会（CNCF）的使用认证，并推出了全新的Kyverno认证助理（KCA）考试。
formalized with 可以译为“规范化。。。” 

建议：

开源的 Kubernetes 策略引擎技术 Kyverno 已获得云原生计算基金会（CNCF）的使用认证，并随着在本月于盐湖城举办的 KubeCon + CloudNativeCon 北美大会上新推出的 Kyverno 认证助理（KCA）考试而进一步规范化。

2024-11-22 03:55 UTC, zRich commented on blog/CNCF Automate Kubernetes SecOps With Kyverno.md
> +作为Kurbenetes的策略引擎技术，它能够验证，修改和生成配置，使安全策略作为代码得以自动化管理，超越了传统的审计和强制执行功能。由于其简单性和丰富的功能，Kubernetes平台工程团队广泛时使用Kyvverno。这些团队利用Kubernetes作为可组合的平台来构建内部开发者平台（IDP）。
最后2句，广泛时使用.... 表述不通顺。建议：

因其简单性和功能丰富，使用 Kubernetes 作为构建内部开发者平台（IDP）的可组合平台的工程团队广泛采用了 Kyverno。

2024-11-22 03:55 UTC, zRich commented on blog/CNCF Automate Kubernetes SecOps With Kyverno.md
> +Nirmata联合创始人兼首席执行官Jim Bugwadia表示，"我们很高兴与CNCF和Linux基金会教育联合推出Kyverno认证助理(CKA)考试。Kubernetes承载了跨所有主要行业的关键工作负载，而Kyverno已成为通过策略作为代码来自动化安全和操作的不可或缺的工具。通过这一认证，Kubernetes管理员将能够评估其在Kyverno上的专业知识，并证明其为组织解决关键用例的能
CKA应该是KCA。

“Kubernetes 承载了跨所有主要行业的关键工作负载“，表述太过确定。
后一句建议翻译成：

Kubernetes 在所有主要行业都承载着关键工作负载，而 Kyverno 凭借其将策略作为代码来实现安全和操作自动化的能力，已成为不可或缺的工具。

2024-11-22 03:55 UTC, zRich commented on blog/CNCF Automate Kubernetes SecOps With Kyverno.md
> +CNCF与Linux基金会教育目前提供一门专注于Kyverno的课程《掌握Kyverno的kubernetes安全》(LFS255),并在KubeCon+CloudNativeCon 2024上发布了Kyverno认证助理(KCA)考试。
课程名称有正式中文名吗？如果有就用正式的名称，如果没有建议使用《运用 Kyverno 掌握 Kubernetes 安全》（LFS255）

2024-11-23 05:37 UTC, zRich approved these changes

2024-11-23 05:39 UTC, merged